### ISSUE TITLE
Require Code

### ISSUE THREAD

**Issue by Thinksky5124** [ahstarwab/real_time_AR#1]
I am very interested to your paper _Efficient Two-Stream Network for Online Video Action Segmentation_ 
 (https://doi.org/10.1109/ACCESS.2022.3201208). But I can't find code related to this paper, and when I reproduced result in paper by the guideline in paper, I reach a great gap comparing with paper experiment result. Would you please release this paper for me? And I will very glad to you!

**Comment by ahstarwab** [comment]
Thanks for your interest in our work, and feel so sorry that I couldn't find my codes for now. (This work was done when I was in school, and I will upload the codes if I can find it.)

I guess that the performance gap can occur for two reasons.

1. I remember that I used onecycleLR scheduler, with more than 100 epochs..   (I should have not use it for strictly fair comparison...)
2. I remember that the over-segmentation error occurs badly, even though the trained model yields somewhat reasonable outputs. Therefore, careful threshold settings are important for post-processing. 

Sorry for not being of any help

**Comment by Thinksky5124** [comment]
Thank you for your partial and timely response! Your advices help me resolve some doubts!
